all:
	pandoc --section-divs -t revealjs -s -o index.html slides.md

theme:
	pandoc --section-divs -t revealjs -s -o blood.html slides.md -V theme:blood
	pandoc --section-divs -t revealjs -s -o beige.html slides.md -V theme:beige
	pandoc --section-divs -t revealjs -s -o black.html slides.md -V theme:black
	pandoc --section-divs -t revealjs -s -o blood.html slides.md -V theme:blood
	pandoc --section-divs -t revealjs -s -o league.html slides.md -V theme:league
	pandoc --section-divs -t revealjs -s -o moon.html slides.md -V theme:moon
	pandoc --section-divs -t revealjs -s -o night.html slides.md -V theme:night
	pandoc --section-divs -t revealjs -s -o serif.html slides.md -V theme:serif
	pandoc --section-divs -t revealjs -s -o simple.html slides.md -V theme:simple
	pandoc --section-divs -t revealjs -s -o sky.html slides.md -V theme:sky
	pandoc --section-divs -t revealjs -s -o solarized.html slides.md -V theme:solarized
	pandoc --section-divs -t revealjs -s -o white.html slides.md -V theme:white
