---
- hosts: server
  tasks:
    - git:
        repo: https://github.com/danielgracia/quero_time.git
        dest: /srv/quero_time
        force: yes
    - gem:
        name: rake
        state: latest
    - gem:
        name: bundler
        state: latest
    - bundler:
        state: latest
        chdir: /srv/quero_time
    - copy:
        src: ../files/nginx/sites-available/default
        dest: /etc/nginx/sites-available/default
    - name: restart nginx
      service: name=nginx state=restarted
    - name: verifica se o arquivo server.pid existe
      stat:
        path: /srv/quero_time/tmp/pids/server.pid
      register: server_pid
    - name: kill rails
      shell: "cat tmp/pids/server.pid | xargs kill"
      args:
        chdir: /srv/quero_time
      when: server_pid.stat.exists == True
    - name: preprocessa os arquivos
      command: "bin/rails assets:precompile db:migrate"
      environment:
        RAILS_ENV: production
      args:
        chdir: /srv/quero_time
    - name: sobe o rails
      command: "bin/rails server -d -e production"
      environment:
        RAILS_ENV: production
      args:
        chdir: /srv/quero_time
